# Generated by Django 3.1.3 on 2020-11-21 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.IntegerField(unique=True)),
                ('username', models.CharField(max_length=20)),
                ('email_address', models.CharField(max_length=36)),
                ('password', models.CharField(max_length=16)),
                ('isCustomer', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.IntegerField()),
                ('orderId', models.IntegerField(unique=True)),
                ('description', models.TextField(max_length=123)),
            ],
        ),
    ]
