# Generated by Django 3.1.3 on 2020-12-11 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='latest_location',
            field=models.CharField(default='Beijing, Chinal', max_length=32),
        ),
    ]
