# Generated by Django 3.1.3 on 2020-12-12 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_order_latest_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
    ]
