# Generated by Django 3.1.3 on 2020-12-12 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_order_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='user',
            new_name='user_id',
        ),
    ]
