# Generated by Django 3.1.3 on 2020-12-12 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20201212_0852'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='user_id',
            new_name='username',
        ),
    ]
